REPO_ROOT = File.join File.dirname(__FILE__), ".."

ZIP_SIP = File.join(REPO_ROOT, "spec", "test-sips", "ateam.zip")
TAR_SIP = File.join(REPO_ROOT, "spec", "test-sips", "ateam.tar")
ZIP_SIP_NODIR = File.join(REPO_ROOT, "spec", "test-sips", "ateam-nodir.zip")
TAR_SIP_NODIR = File.join(REPO_ROOT, "spec", "test-sips", "ateam-nodir.tar")
ZIP_NO_DESCRIPTOR = File.join(REPO_ROOT, "spec", "test-sips", "ateam-nodesc.zip")
ZIP_DMD_METADATA = File.join(REPO_ROOT, "spec", "test-sips", "ateam-dmd.zip")
ZIP_BROKEN_DESCRIPTOR = File.join(REPO_ROOT, "spec", "test-sips", "ateam-broken-descriptor.zip")
ZIP_BAD_PROJECT = File.join(REPO_ROOT, "spec", "test-sips", "ateam-bad-project.zip")
ZIP_BAD_ACCOUNT = File.join(REPO_ROOT, "spec", "test-sips", "ateam-bad-account.zip")
ZIP_NO_CONTENT_FILES = File.join(REPO_ROOT, "spec", "test-sips", "ateam-missing-contentfile.zip")
ZIP_CHECKSUM_MISMATCH = File.join(REPO_ROOT, "spec", "test-sips", "ateam-checksum-mismatch.zip")
ZIP_INVALID_DESCRIPTOR = File.join(REPO_ROOT, "spec", "test-sips", "ateam-invalid-descriptor.zip")
ZIP_UNKNOWN_CHECKSUM_TYPE = File.join(REPO_ROOT, "spec", "test-sips", "ateam-unknown-checksum-type.zip")
ZIP_MISSING_CHECKSUM = File.join(REPO_ROOT, "spec", "test-sips", "ateam-missing-checksum.zip")
ZIP_LONG_PACKAGE_NAME = File.join(REPO_ROOT, "spec", "test-sips", "ateam-long-package-name.zip")
ZIP_INVALID_CHAR_IN_NAME = File.join(REPO_ROOT, "spec", "test-sips", "ateam-invalid-char-in-name.zip")
ZIP_NO_DESCRIBED_CONTENT_FILE = File.join(REPO_ROOT, "spec", "test-sips", "ateam-no-described-content-file.zip")
ZIP_INVALID_DATAFILE_NAME = File.join(REPO_ROOT, "spec", "test-sips", "ateam-invalid-datafile-name.zip")
ZIP_MULTIPLE_PROBLEMS = File.join(REPO_ROOT, "spec", "test-sips", "ateam-multiple-problems.zip")
NOT_AN_ARCHIVE = File.join(REPO_ROOT, "spec", "test-sips", "not-an-archive")
NOT_VALID_ARCHIVE = __FILE__

NORMAL_WIP = File.join(REPO_ROOT, "spec", "wips", "normal_wip.zip")
TWO_UNDESCRIBED_FILES = File.join(REPO_ROOT, "spec", "wips", "two_undescribed.zip")
INVALID_ACCOUNT = File.join(REPO_ROOT, "spec", "wips", "invalid_account.zip")
INVALID_PROJECT = File.join(REPO_ROOT, "spec", "wips", "invalid_project.zip")
MISSING_CONTENT_FILE = File.join(REPO_ROOT, "spec", "wips", "missing_content_file.zip")
UNDESCRIBED_CONTENT_FILE = File.join(REPO_ROOT, "spec", "wips", "undescribed_content_file.zip")
MISSING_UNDESCRIBED_CONTENT_FILE = File.join(REPO_ROOT, "spec", "wips", "missing_undescribed_content_file.zip")
SHA1_MISMATCH = File.join(REPO_ROOT, "spec", "wips", "sha1_mismatch.zip")
MD5_MISMATCH = File.join(REPO_ROOT, "spec", "wips", "md5_mismatch.zip")
INFER_MD5 = File.join(REPO_ROOT, "spec", "wips", "infer_md5.zip")
INFER_SHA1 = File.join(REPO_ROOT, "spec", "wips", "infer_sha1.zip")
CANT_INFER_CHECKSUM_TYPE = File.join(REPO_ROOT, "spec", "wips", "cant_infer.zip")
UNKNOWN_CHECKSUM_TYPE = File.join(REPO_ROOT, "spec", "wips", "unknown_checksum_type.zip")
MISSING_CHECKSUM_DATA = File.join(REPO_ROOT, "spec", "wips", "missing_checksum_data.zip")
PACKAGE_NAME_STARTS_DOT = File.join(REPO_ROOT, "spec", "wips", "package_name_starts_dot.zip")
PACKAGE_NAME_HAS_SPACE = File.join(REPO_ROOT, "spec", "wips", "package_name_has_space.zip")
PACKAGE_NAME_HAS_QUOTE = File.join(REPO_ROOT, "spec", "wips", "package_name_has_quote.zip")
PACKAGE_NAME_LONG = File.join(REPO_ROOT, "spec", "wips", "package_name_long.zip")
INVALID_DATAFILE_NAME = File.join(REPO_ROOT, "spec", "wips", "invalid_datafile_name.zip")



